# Generated by Django 5.0.6 on 2024-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('items', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
