# Generated by Django 5.0.6 on 2024-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seat_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
